PREFIX default: <http://group10.com/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ns: <http://group10.com/>

# Show all the elements of the ontology, including the class to each one belongs to:

SELECT DISTINCT ?x ?y
WHERE
{
  ?x rdf:type ?y
}


# See all the classes of the ontology:

SELECT DISTINCT ?x
WHERE
{
  ?x a owl:Class
}


# See all the instances of the example:

SELECT DISTINCT ?x
WHERE
{
  ?x a ?y
  ?x a owl:Class.
}


# See all IRIs

SELECT DISTINCT ?x
WHERE
{
  ?x a owl:sameAs
}