PREFIX vocab: <http://eit-upm-opendata.com/ted#> .
PREFIX owl: <http://www.w3.org/2002/07/owl#> .
PREFIX pproc: <http://contsem.unizar.es/def/sector-publico/pproc#> .
PREFIX schema: <http://schema.org/> .

# Check if entity link is to Prudnik on wikidata
SELECT ?prudnik_link
WHERE {
    <http://eit-upm-opendata.com/ted/Town/Prudnik> owl:sameAs ?prudnik_link .
}

# List of contract notices
SELECT ?contractNotices
WHERE {
    ?contractNotices a pproc:ContractNotice .
}
LIMIT 15

# List of contract bodies
SELECT ?contractBodies
WHERE {
    ?contractBodies a pproc:ContractBodies .
}
LIMIT 15

# Distinct contractors per country
SELECT ?country (COUNT(?contractBodies) as ?count)
WHERE { 
    ?contractBodies a pproc:ContractBodies .
    ?contractBodies schema:addressCountry ?country
}
GROUP BY ?country
ORDER BY desc(?count)
