# -*- coding: utf-8 -*-
"""Task03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RWpOwiJnutHG61G0wjWbp2wsjYBVLvsH

**TASK 3: Statement-based query**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2020-2021/master/Assignment4"

"""Import example3.rdf to our graph"""

from rdflib import Graph, Namespace, Literal
g = Graph()
g.parse(github_storage+"/resources/example3.rdf", format="xml")

"""We list all the resources with the property VCARD:FN"""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

for s,p,o in g.triples((None, VCARD.FN, None)):
  print(s)

"""We now list the full name (VCARD: FN) of these resources"""

for s,p,o in g.triples((None, VCARD.FN, None)):
  print(o)

"""We now list all the resources that have the family name "Smith", we must take into account the type of data of our literals when performing searches. In our example the literals are typed as XSD String (http://www.w3.org/2001/XMLSchema#string) and when searching we must indicate it, otherwise the comparison will fail even though the text strings are the same"""

from rdflib import XSD
for t in g.triples((None, VCARD.Family, Literal('Smith', datatype=XSD.string))):
  print(t)

print(Literal(1, datatype=XSD.number).eq(Literal("1", datatype=XSD.string)))
print(Literal(1, datatype=XSD.number).eq(Literal(1, datatype=XSD.string)))
print(Literal(1).eq(Literal(1, datatype=XSD.number)))
print(Literal(1, datatype=XSD.number).eq(Literal(1, datatype=XSD.number)))
print(Literal(1).datatype)
print(Literal("1").datatype)

"""All resources that have an email"""

FOAF = Namespace("http://xmlns.com/foaf/0.1/")
for s,p,o in g.triples((None, FOAF.email, None)):
  print(s,p,o)

"""We now list all the subjects who know "Jane Smith" (VCARD: FN) by her first name (VCARD: Given). When we know that we are going to obtain a single result, we can use the value function indicating each known parameter (only one must be None)."""

janeSmithURI = g.value(subject=None, predicate=VCARD.FN, object=Literal("Jane Smith"))

knows = g.triples((None, FOAF.knows, janeSmithURI))

for s,p,o in knows:
  
  givenName = g.value(subject=s, predicate=VCARD.Given, object=None)

  print(givenName)