# -*- coding: utf-8 -*-
"""Task00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEMjMWa_EtvKbdyyB31GoLRGUQD89Nm2

**Task 00: Installing and testing RDFlib**

We install the necessary dependencies in our environment. pip is Python's package manager.
"""

!pip install rdflib

"""From the rdflib package we import the necessary classes for the task"""

from rdflib import Graph, Namespace, Literal

"""We create an empty Graph"""

g = Graph()

"""Creating a namespace..."""

app_ns = Namespace("http://example.org/App/")

"""Defining subject, predicate and object that we are going to insert in the Graph"""

app = app_ns.this
says = app_ns.says
hello = Literal("Hola mundo!")

"""In RDFlib triples are defined as a native Python tuple containing 3 elements in order (subject, predicate, and object)."""

triple = (app, says, hello)
g.add(triple)

"""We can iterate over our graph to obtain all the stored triples, with the g.triples () function we can search for those that match the specified pattern. We indicate None where the result is indifferent to us.

Doc: https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.graph.Graph.triples
"""

search = g.triples((None, says, None))

for subj, pred, obj in search:
  print(subj,pred,obj)

"""Additionally, we can also show all triples by serializing our graph in one of the supported formats."""

#@title
print(g.serialize(format="xml").decode("UTF-8"))
