1.Get all the classes
 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?class
WHERE
{
 {?x a ?class} 
 UNION
 {?class rdf:type rdfs:Class}
}
 

2. Get all the subclasses of the class Place
 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex:<http://www.example.org/group07/ontology/>

SELECT DISTINCT ?x ?z

 WHERE

{
 ?x rdfs:subClassOf ex:Place
}
 
 
3.List class hierarchy
 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
SELECT DISTINCT ?subject ?label ?supertype
WHERE {
    { ?subject a owl:Class . } UNION { ?individual a ?subject . } .
    OPTIONAL { ?subject rdfs:subClassOf ?supertype } .
    OPTIONAL { ?subject rdfs:label ?label }
} ORDER BY ?subject
 }​​​​
 
4. Get all project record numbers, together with the coordinator country,ordered by rcn (ascending)
 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex:<http://www.example.org/group07/ontology/>

 
SELECT DISTINCT ?x ?rcn

 WHERE {​​​​
 
?x ex:country ?rcn.
 
?x rdfs:label ?rcn.
 
}​​​​

 order by asc(asc(?rcn))
 


 5.Get all ecContribution with more than 100000
 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex:<http://www.example.org/group07/ontology/>

 
SELECT DISTINCT ?x amonut

 WHERE

 {​​​​​​​​​

 ?x rdf:type/rdfs:subClassOf* ex:Contribution .​

 ?x ex:Contribution ?amount.
 
}​​​​​​​​​

 FILTER ((?amount)^xsd:double > 100000)

 }​​​​​​​​​
 
LIMIT 100
 
6. Describe the resource with  rdfs:label "Jan Gieseler”
 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex:<http://www.example.org/group07/ontology/>


 DESCRIBE ?x 
 
WHERE{​​​​?x rdfs:label "Jan Gieseler" .

 }​​​​

7. Get all instance of class Organization

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex:<http://www.example.org/group07/ontology/>

 
SELECT DISTINCT ?x

 WHERE

 {

 ?x a/rdfs:subClassOf* ex:organization.

 } LIMIT 100
 
8. Get all resouces of status "closed"

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex:<http://www.example.org/group07/ontology/>

 SELECT DISTINCT ?x ?status
 WHERE
{
	?x ex:status ?status .
	FILTER regex(?status, "^CLOSED")
}

 LIMIT 100
