# 1. Get all properties of Contract, except rdf:type

PREFIX vocab: <http://group01.org/aragon/ontology/>
SELECT DISTINCT ?prop
WHERE {
    ?contract a vocab:Contract .
    ?contract ?prop ?x .
    FILTER (?prop != rdf:type) }

# 2. Get all classes

PREFIX vocab: <http://group01.org/aragon/ontology/>
SELECT DISTINCT ?class
WHERE {
    {?x a ?class} 
    UNION
    {?class a rdfs:Class}
}

# 3. Get the number of triples

PREFIX vocab: <http://group01.org/aragon/ontology/>
SELECT COUNT(?x)
WHERE {
    ?x ?y ?z }

# 4. Get the contracts with an award price greater than 10000

PREFIX vocab: <http://group01.org/aragon/ontology/>
SELECT DISTINCT ?contract
WHERE {
    ?contract vocab:hasAwardPrice ?price .
    FILTER (?price > 10000) }